// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// This pipeline builds the AAOS builder Docker image using Kaniko
// rather than use a Docker to avoid docker in docker privilege issues.
//
// References:
//   * https://github.com/GoogleContainerTools/kaniko
pipeline {
  agent {
    kubernetes {
      yaml """\
        apiVersion: v1
        kind: Pod
        spec:
          hostname: jenkins-aaos-build-pod
          serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            imagePullPolicy: IfNotPresent
            command:
            - /busybox/cat
            tty: true
      """.stripIndent()
    }
  }

  // Block concurrent builds to avoid clashing.
  options {
    buildBlocker (useBuildBlocker: true, blockLevel: 'GLOBAL', scanQueueFor: 'BUILDABLE', blockingJobs: '.*Docker.*')
  }

  parameters {
    string(name: 'IMAGE_TAG', defaultValue: 'latest', description: '<p>Image tag for the builder image.</p>')
    booleanParam(name: 'NO_PUSH', defaultValue: true, description: '<p>Build only, do not push to registry.</p>')
  }

  environment {
    // Update latest tag.
    DESTINATION="--destination=${env.CLOUD_REGION}-docker.pkg.dev/${env.CLOUD_PROJECT}/${env.ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}"
    KANIKO_OPTIONS="${NO_PUSH == "true" ? "--no-push" : "${DESTINATION}:${IMAGE_TAG}"}"
  }

  stages {
    stage ('Create Docker Image'){
      when { expression { env.IMAGE_TAG } }
      steps {
        container(name: 'kaniko') {
          script {
            currentBuild.description = "$BUILD_USER"
          }
          sh '''
            # Build the docker image and push to Artifact registry using service account configured with
            # correct roles/permissions.
            /kaniko/executor -f workloads/android/pipelines/environment/docker_image_template/Dockerfile \
              -c workloads/android/pipelines/environment/docker_image_template --skip-tls-verify-pull \
              --insecure --skip-tls-verify "${KANIKO_OPTIONS}"
          '''
        }
      }
    }
  }
}
